#!/bin/sh
# Add Alias Here (Source this file in your zshrc/bashrc file )

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytp="yt -o \"%(playlist_index)s-%(title)s.%(ext)s\""\
	lofi="mpv --no-video https://www.youtube.com/watch\?v\=5qap5aO4i9A"\
	ffmpeg="ffmpeg -hide_banner"\
	x="startx"
# Abbrevation for long Commands
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	p="sudo pacman" \
	y='yay'	\
	emu="scrcpy -m 1920"\
	SS="sudo systemctl"\
	zshrc="e $ZDOTDIR/.zshrc"\
	ws="wal -i $HOME/Pictures/wallpapers"\
	note="nvim ~/Documents/Notes/notes_$(date +"%Y-%m-%d_%H:%M").md"\

alias rec-new-key='gpg --keyserver pool.sks-keyservers.net --recv-keys'

alias ls='ls --color=auto'
alias ll='ls -l'
alias l='ls -lFh --color=auto'     
alias la='ls -lAFh --color=auto'  
alias lr='ls -tRFh --color=auto' 
alias lt='ls -ltFh --color=auto'
alias ll='ls -l --color=auto' 
alias ..='cd ..'
alias dev='cd ~/Developer'
alias idea='idea.sh'
alias Powershell='pwsh'
# git alias ->
alias ga='git add'
alias gaa='git add .'
alias gaaa='git add -A'
alias gc='git commit'
alias gcm='git commit -m'
alias gd='git diff'
alias gi='git init'
alias gl='git log'
alias gp='git pull'
alias gpsh='git push'
alias gss='git status -s'
alias gs='figlet -f small DONT FORGET TO PULL ; echo "\n" ; git status'
