#!/bin/sh
# Add Alias Here (Source this file in your zshrc/bashrc file )

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Abbrevation for long Commands
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	p="sudo pacman" \
	y='yay'	\
	emu="scrcpy -m 1920"\
	SS="sudo systemctl"\
	zshrc="e .config/zsh/.zshrc"\
	ws="wal -i $HOME/Pictures/wallpapers"
	
